# Site settings
course_name: Database Systems
course_description: "This course studies the management of large bodies of information. This includes schemes for the representation, manipulation, and storage of complex information structures as well as algorithms for processing these structures efficiently and for retrieving the information they contain. The course does include programming in Python. The course topics include Relational Databases and SQL and NOSQL (Not Only SQL) data stores."
course_semester: "Winter 2025"

baseurl: "/winter2025" # the subpath of your site, e.g. /blog/
url: "http://ccpalmer.github.io/" # the base hostname & protocol for your site

schoolname: "Dartmouth College"
schoolurl: "https://dartmouth.edu"
twitter_username: drcybersecurity 

address: |
    15 Thayer Drive
    Hanover
    New Hampshire

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
